# Generated by Django 2.2.7 on 2019-12-03 03:54

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=mdeditor.fields.MDTextField(max_length=128, verbose_name='文章标题'),
        ),
    ]
