# Generated by Django 2.2.7 on 2019-12-06 06:50

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191205_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='唯一UUID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', mdeditor.fields.MDTextField(max_length=128, verbose_name='文章标题')),
                ('status', models.CharField(choices=[(-1, 'cancer'), (0, 'waiting'), (1, 'running'), (2, 'finish')], max_length=32, verbose_name='分组')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
