# Generated by Django 2.2.7 on 2019-12-06 06:51

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=mdeditor.fields.MDTextField(max_length=128, verbose_name='内容'),
        ),
    ]
