# Generated by Django 2.2.7 on 2019-12-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191206_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[(-1, 'cancer'), (0, 'waiting'), (1, 'running'), (2, 'finish')], max_length=32, verbose_name='状态'),
        ),
    ]
