# Generated by Django 2.2.7 on 2019-12-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191209_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'cancer'), (0, 'waiting'), (1, 'running'), (2, 'finish')], verbose_name='状态'),
        ),
    ]
