# Generated by Django 2.2.7 on 2019-11-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20191125_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoBasicModel',
        ),
    ]
