# Generated by Django 2.2.7 on 2019-12-03 03:15

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demo', '0003_delete_demobasicmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='唯一UUID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512, verbose_name='测试字段')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
